<a href="https://colab.research.google.com/github/abidshafee/google.colaboratory_projects/blob/master/NLP_Natural_Language_Processing_Using_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tokenization
api involves: **Tokenizer** from **tensorflow->compat.v2->keras->preprocessing.txt**

Given sentences encoding into numbers is calles Tokenization

In [28]:
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from tensorflow.keras.preprocessing.sequence import pad_sequences
# from tensorflow.keras.preprocessing.txt import Tokenizer

In [19]:
sentences = ['The first step in sentence classification is to represent variable-length sentences using neural networks.', 'In this section, I’m going to present the concept of recurrent neural networks (RNNs), one of the most important concepts in deep NLP.', 'Many modern NLP models use RNNs in some way.', 'I’ll explain why they’re important, what they do, and introduce their simplest variant.']

In [25]:
tokenizer = tf.compat.v2.keras.preprocessing.text.Tokenizer(num_words=100, oov_token='<OOV>')
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
print(word_index)

{'<OOV>': 1, 'in': 2, 'the': 3, 'to': 4, 'neural': 5, 'networks': 6, 'of': 7, 'rnns': 8, 'important': 9, 'nlp': 10, 'first': 11, 'step': 12, 'sentence': 13, 'classification': 14, 'is': 15, 'represent': 16, 'variable': 17, 'length': 18, 'sentences': 19, 'using': 20, 'this': 21, 'section': 22, 'i’m': 23, 'going': 24, 'present': 25, 'concept': 26, 'recurrent': 27, 'one': 28, 'most': 29, 'concepts': 30, 'deep': 31, 'many': 32, 'modern': 33, 'models': 34, 'use': 35, 'some': 36, 'way': 37, 'i’ll': 38, 'explain': 39, 'why': 40, 'they’re': 41, 'what': 42, 'they': 43, 'do': 44, 'and': 45, 'introduce': 46, 'their': 47, 'simplest': 48, 'variant': 49}


In [26]:
word_index.keys()

dict_keys(['<OOV>', 'in', 'the', 'to', 'neural', 'networks', 'of', 'rnns', 'important', 'nlp', 'first', 'step', 'sentence', 'classification', 'is', 'represent', 'variable', 'length', 'sentences', 'using', 'this', 'section', 'i’m', 'going', 'present', 'concept', 'recurrent', 'one', 'most', 'concepts', 'deep', 'many', 'modern', 'models', 'use', 'some', 'way', 'i’ll', 'explain', 'why', 'they’re', 'what', 'they', 'do', 'and', 'introduce', 'their', 'simplest', 'variant'])

In [27]:
word_index.values()

dict_values([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

# Organizing text by Sequencing - Turning Sentences into data

In [23]:
sequences = tokenizer.texts_to_sequences(sentences)
print(sequences)

[[2, 10, 11, 1, 12, 13, 14, 3, 15, 16, 17, 18, 19, 4, 5], [1, 20, 21, 22, 23, 3, 24, 2, 25, 6, 26, 4, 5, 7, 27, 6, 2, 28, 8, 29, 1, 30, 9], [31, 32, 9, 33, 34, 7, 1, 35, 36], [37, 38, 39, 40, 8, 41, 42, 43, 44, 45, 46, 47, 48]]


In [37]:
# pad_sequences() is a method to handle sentences of different lengths
# best way to handle sentence length is using raggedtensor, we might discuss it in another scope
# but for simplicity we uses here the pad_sequence() to deal with sentence length
padded = pad_sequences(sequences)
print(padded)

# pad_sequences accept parameters are follows: 
#  - padding='post' - will add 0s after the sentences
#  - maxlen=5 - maxlen parameter specify the desire lengh
#  - truncating='post' - specify the choping off the later post if sentence exided 'maxlen'

[[ 0  0  0  0  0  0  0  0  2 10 11  1 12 13 14  3 15 16 17 18 19  4  5]
 [ 1 20 21 22 23  3 24  2 25  6 26  4  5  7 27  6  2 28  8 29  1 30  9]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 31 32  9 33 34  7  1 35 36]
 [ 0  0  0  0  0  0  0  0  0  0 37 38 39 40  8 41 42 43 44 45 46 47 48]]
