<a href="https://colab.research.google.com/github/abidshafee/google.colaboratory_projects/blob/master/NLP_Natural_Language_Processing_Using_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tokenization
api involves: **Tokenizer** from **tensorflow->compat.v2->keras->preprocessing.txt**

Given sentences encoding into numbers is calles Tokenization

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.compat.v2.keras.preprocessing.text import Tokenizer
# from tensorflow.keras.preprocessing.txt import Tokenizer

In [ ]:
sentences = ['The first step in sentence classification is to represent variable-length sentences using neural networks.', 'In this section, I’m going to present the concept of recurrent neural networks (RNNs), one of the most important concepts in deep NLP.', 'Many modern NLP models use RNNs in some way.', 'I’ll explain why they’re important, what they do, and introduce their simplest variant.']

In [ ]:
tokenizer = Tokenizer(num_words=100, oov_token='<OOV>')
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
# print(word_index)

In [ ]:
word_index.keys()

dict_keys(['<OOV>', 'in', 'the', 'to', 'neural', 'networks', 'of', 'rnns', 'important', 'nlp', 'first', 'step', 'sentence', 'classification', 'is', 'represent', 'variable', 'length', 'sentences', 'using', 'this', 'section', 'i’m', 'going', 'present', 'concept', 'recurrent', 'one', 'most', 'concepts', 'deep', 'many', 'modern', 'models', 'use', 'some', 'way', 'i’ll', 'explain', 'why', 'they’re', 'what', 'they', 'do', 'and', 'introduce', 'their', 'simplest', 'variant'])

In [ ]:
word_index.values()

dict_values([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

# Organizing text by Sequencing - Turning Sentences into data

In [ ]:
sequences = tokenizer.texts_to_sequences(sentences)
print(sequences)

[[2, 10, 11, 1, 12, 13, 14, 3, 15, 16, 17, 18, 19, 4, 5], [1, 20, 21, 22, 23, 3, 24, 2, 25, 6, 26, 4, 5, 7, 27, 6, 2, 28, 8, 29, 1, 30, 9], [31, 32, 9, 33, 34, 7, 1, 35, 36], [37, 38, 39, 40, 8, 41, 42, 43, 44, 45, 46, 47, 48]]


In [ ]:
# pad_sequences() is a method to handle sentences of different lengths
# best way to handle sentence length is using raggedtensor, we might discuss it in another scope
# but for simplicity we uses here the pad_sequence() to deal with sentence length
padded = pad_sequences(sequences)
print(padded)

# pad_sequences accept parameters are follows: 
#  - padding='post' - will add 0s after the sentences
#  - maxlen=5 - maxlen parameter specify the desire lengh
#  - truncating='post' - specify the choping off the later post if sentence exided 'maxlen'

[[ 0  0  0  0  0  0  0  0  2 10 11  1 12 13 14  3 15 16 17 18 19  4  5]
 [ 1 20 21 22 23  3 24  2 25  6 26  4  5  7 27  6  2 28  8 29  1 30  9]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 31 32  9 33 34  7  1 35 36]
 [ 0  0  0  0  0  0  0  0  0  0 37 38 39 40  8 41 42 43 44 45 46 47 48]]


# Sentiment Analysis - recognize sentiment in text

In [ ]:
import json

In [ ]:
from google.colab import files
upload = files.upload()

Saving sarcasm.json to sarcasm.json


In [ ]:
with open('sarcasm.json', 'r') as f:
  datastore = json.load(f)

In [ ]:
sentences = []
labels = []
urls = []

for item in datastore:
  sentences.append(item['headline'])
  labels.append(item['is_sarcastic'])
  urls.append(item['article_link'])

In [ ]:
# sentences

In [ ]:
# labels
# urls
len(labels)

26709

In [ ]:
tokenizer = Tokenizer(oov_token="<OOV>")
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index

In [ ]:
# now turning the sentences sequence of token
sequences = tokenizer.texts_to_sequences(sentences)
paded = pad_sequences(sequences, padding='post')

In [ ]:
len(sequences)

26709

In [ ]:
paded[1]
# paded.shape

array([   4, 8435, 3338, 2746,   22,    2,  166, 8436,  416, 3112,    6,
        258,    9, 1002,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [ ]:
paded.shape

(26709, 40)

In [ ]:
# now spliting data into traning and testing sets
# let training_size = 80% of data; 26709*80% using python slicing

training_size = 21000

training_sentences = sentences[:training_size]
testing_sentences = sentences[training_size:]

# spliting labels into training and testing sets
training_labels = labels[:training_size]
testing_labels = labels[training_size:]


In [ ]:
# now tekenize trainig and testing set seperately

tokenizer = Tokenizer(num_words=training_size, oov_token=None)
tokenizer.fit_on_texts(training_sentences)
word_index = tokenizer.word_index

In [ ]:
# word_index

training_sequences = tokenizer.texts_to_sequences(training_sentences)
training_paded = pad_sequences(training_sequences)
training_paded

array([[    0,     0,     0, ...,     5,  2711,  9172],
       [    0,     0,     0, ...,   254,     8,   945],
       [    0,     0,     0, ...,    44,     1,  9173],
       ...,
       [    0,     0,     0, ..., 12473,  5960,   496],
       [    0,     0,     0, ...,     3,   363,   311],
       [    0,     0,     0, ...,    19,  3769,   937]], dtype=int32)

In [ ]:
testing_sequences = tokenizer.texts_to_sequences(testing_sentences)
testing_paded = pad_sequences(testing_sequences)
testing_paded

array([[    0,     0,     0, ...,   369,  1316,  5075],
       [    0,     0,     0, ...,     0,     0,  5478],
       [    0,     0,     0, ..., 13430,     7, 14891],
       ...,
       [    0,     0,     0, ...,     0,     8,    67],
       [    0,     0,     0, ...,  1724,  3788,  3483],
       [    0,     0,     0, ...,     5,     3,   800]], dtype=int32)

In [ ]:
# converting to numpy array explicitely for recent version of tf
training_paded = np.array(training_paded)
training_labels = np.array(training_labels)
testing_paded = np.array(testing_paded)
testing_labels = np.array(testing_labels)

# Model

In [ ]:
model = tf.keras.Sequential([
                             tf.keras.layers.Embedding(training_size, output_dim=11),
                             tf.keras.layers.GlobalAveragePooling1D(),
                             tf.keras.layers.Dense(21, activation = 'relu'),
                             tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
epoch_no = 22
training_texts = model.fit(trainig_paded, training_labels, epochs=epoch_no,
                           validation_data=(testing_paded, testing_labels), verbose=2)

Epoch 1/22
657/657 - 3s - loss: 2.6187e-07 - accuracy: 1.0000 - val_loss: 2.7604 - val_accuracy: 0.7996
Epoch 2/22
657/657 - 2s - loss: 1.9746e-07 - accuracy: 1.0000 - val_loss: 2.8533 - val_accuracy: 0.8010
Epoch 3/22
657/657 - 2s - loss: 2.1649e-07 - accuracy: 1.0000 - val_loss: 2.8884 - val_accuracy: 0.8001
Epoch 4/22
657/657 - 2s - loss: 1.2021e-07 - accuracy: 1.0000 - val_loss: 2.9464 - val_accuracy: 0.7991
Epoch 5/22
657/657 - 2s - loss: 8.7810e-08 - accuracy: 1.0000 - val_loss: 3.0225 - val_accuracy: 0.8001
Epoch 6/22
657/657 - 2s - loss: 2.0205e-06 - accuracy: 1.0000 - val_loss: 3.0462 - val_accuracy: 0.8014
Epoch 7/22
657/657 - 3s - loss: 4.0002e-07 - accuracy: 1.0000 - val_loss: 3.0748 - val_accuracy: 0.8015
Epoch 8/22
657/657 - 2s - loss: 1.1827e-07 - accuracy: 1.0000 - val_loss: 3.0730 - val_accuracy: 0.7996
Epoch 9/22
657/657 - 2s - loss: 7.0876e-08 - accuracy: 1.0000 - val_loss: 3.0813 - val_accuracy: 0.7991
Epoch 10/22
657/657 - 2s - loss: 5.5717e-08 - accuracy: 1.0000 -

In [ ]:
print(training_texts)

# Testing Model on New sentences

In [ ]:
# now we can predic any sentence using the model. What ever it bias to sarcastic or not
new_sentences = ['The first step in sentence classification is to represent variable-length sentences using neural networks.', 
             'In this section, I’m going to present the concept of recurrent neural networks (RNNs), one of the most important concepts in deep NLP.', 
             'Many modern NLP models use RNNs in some way.', 
             'I’ll explain why they’re important, what they do, and introduce their simplest variant.']

In [ ]:
sequence_sentences = tokenizer.texts_to_sequences(new_sentences)
paded_new_sent = pad_sequences(sequence_sentences)

In [ ]:
paded_new_sent

array([[    0,     0,     0,     0,     0,     0,     0,     3,    54,
         1297,     4,  1470,    10,     1,  6175,  7186,   625, 11079],
       [    4,    19,  1972,   117,     1,  3328,     3,  4077,     2,
        11079,    40,     2,     3,    91,   838, 18717,     4,   942],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,   452,  1672,  3569,   340,     4,   153,    89],
       [    0,     0,     0,     0,     0,     0,     0,     0,  1678,
           46,   838,    31,    95,    90,     8,  4868,    93, 13023]],
      dtype=int32)

In [ ]:
prediction = model.predict(paded_new_sent)

In [ ]:
print(prediction)

[[1.6637588e-22]
 [1.4538986e-15]
 [2.5311798e-02]
 [9.8330289e-01]]


### Ssentiment Analysis in New sentences:
prediction 9 indicating the 4th sentece has a high probability of sarcasm. Less than 5 indicates these sentences are not sercastic at all.

# Training AI to create Poem

In [4]:
data = """Do not go gentle into that good night,
Old age should burn and rave at close of day;
Rage, rage against the dying of the light.

Though wise men at their end know dark is right,
Because their words had forked no lightning they
Do not go gentle into that good night.

Good men, the last wave by, crying how bright
Their frail deeds might have danced in a green bay,
Rage, rage against the dying of the light.

Wild men who caught and sang the sun in flight,
And learn, too late, they grieved it on its way,
Do not go gentle into that good night.

Grave men, near death, who see with blinding sight
Blind eyes could blaze like meteors and be gay,
Rage, rage against the dying of the light.

And you, my father, there on the sad height,
Curse, bless, me now with your fierce tears, I pray.
Do not go gentle into that good night.
Rage, rage against the dying of the light"""

In [5]:
corpus = data.lower().split('\n')

In [6]:
corpus

['do not go gentle into that good night,',
 'old age should burn and rave at close of day;',
 'rage, rage against the dying of the light.',
 '',
 'though wise men at their end know dark is right,',
 'because their words had forked no lightning they',
 'do not go gentle into that good night.',
 '',
 'good men, the last wave by, crying how bright',
 'their frail deeds might have danced in a green bay,',
 'rage, rage against the dying of the light.',
 '',
 'wild men who caught and sang the sun in flight,',
 'and learn, too late, they grieved it on its way,',
 'do not go gentle into that good night.',
 '',
 'grave men, near death, who see with blinding sight',
 'blind eyes could blaze like meteors and be gay,',
 'rage, rage against the dying of the light.',
 '',
 'and you, my father, there on the sad height,',
 'curse, bless, me now with your fierce tears, i pray.',
 'do not go gentle into that good night.',
 'rage, rage against the dying of the light']