<a href="https://colab.research.google.com/github/abidshafee/google.colaboratory_projects/blob/master/NLP_Natural_Language_Processing_Using_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tokenization
api involves: **Tokenizer** from **tensorflow->compat.v2->keras->preprocessing.txt**

Given sentences encoding into numbers is calles Tokenization

In [12]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.compat.v2.keras.preprocessing.text import Tokenizer
# from tensorflow.keras.preprocessing.txt import Tokenizer

In [2]:
sentences = ['The first step in sentence classification is to represent variable-length sentences using neural networks.', 'In this section, I’m going to present the concept of recurrent neural networks (RNNs), one of the most important concepts in deep NLP.', 'Many modern NLP models use RNNs in some way.', 'I’ll explain why they’re important, what they do, and introduce their simplest variant.']

In [3]:
tokenizer = Tokenizer(num_words=100, oov_token='<OOV>')
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
# print(word_index)

In [4]:
word_index.keys()

dict_keys(['<OOV>', 'in', 'the', 'to', 'neural', 'networks', 'of', 'rnns', 'important', 'nlp', 'first', 'step', 'sentence', 'classification', 'is', 'represent', 'variable', 'length', 'sentences', 'using', 'this', 'section', 'i’m', 'going', 'present', 'concept', 'recurrent', 'one', 'most', 'concepts', 'deep', 'many', 'modern', 'models', 'use', 'some', 'way', 'i’ll', 'explain', 'why', 'they’re', 'what', 'they', 'do', 'and', 'introduce', 'their', 'simplest', 'variant'])

In [5]:
word_index.values()

dict_values([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

# Organizing text by Sequencing - Turning Sentences into data

In [6]:
sequences = tokenizer.texts_to_sequences(sentences)
print(sequences)

[[3, 11, 12, 2, 13, 14, 15, 4, 16, 17, 18, 19, 20, 5, 6], [2, 21, 22, 23, 24, 4, 25, 3, 26, 7, 27, 5, 6, 8, 28, 7, 3, 29, 9, 30, 2, 31, 10], [32, 33, 10, 34, 35, 8, 2, 36, 37], [38, 39, 40, 41, 9, 42, 43, 44, 45, 46, 47, 48, 49]]


In [7]:
# pad_sequences() is a method to handle sentences of different lengths
# best way to handle sentence length is using raggedtensor, we might discuss it in another scope
# but for simplicity we uses here the pad_sequence() to deal with sentence length
padded = pad_sequences(sequences)
print(padded)

# pad_sequences accept parameters are follows: 
#  - padding='post' - will add 0s after the sentences
#  - maxlen=5 - maxlen parameter specify the desire lengh
#  - truncating='post' - specify the choping off the later post if sentence exided 'maxlen'

[[ 0  0  0  0  0  0  0  0  3 11 12  2 13 14 15  4 16 17 18 19 20  5  6]
 [ 2 21 22 23 24  4 25  3 26  7 27  5  6  8 28  7  3 29  9 30  2 31 10]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 32 33 10 34 35  8  2 36 37]
 [ 0  0  0  0  0  0  0  0  0  0 38 39 40 41  9 42 43 44 45 46 47 48 49]]


# Sentiment Analysis - recognize sentiment in text

In [8]:
import json

In [9]:
from google.colab import files
upload = files.upload()

Saving sarcasm.json to sarcasm.json


In [10]:
with open('sarcasm.json', 'r') as f:
  datastore = json.load(f)

In [11]:
sentences = []
labels = []
urls = []

for item in datastore:
  sentences.append(item['headline'])
  labels.append(item['is_sarcastic'])
  urls.append(item['article_link'])

In [12]:
# sentences

In [13]:
# labels
# urls
len(labels)

26709

In [14]:
tokenizer = Tokenizer(oov_token="<OOV>")
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index

In [15]:
# now turning the sentences sequence of token
sequences = tokenizer.texts_to_sequences(sentences)
paded = pad_sequences(sequences, padding='post')

In [16]:
len(sequences)

26709

In [17]:
paded[1]
# paded.shape

array([   4, 8435, 3338, 2746,   22,    2,  166, 8436,  416, 3112,    6,
        258,    9, 1002,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [18]:
paded.shape

(26709, 40)

In [19]:
# now spliting data into traning and testing sets
# let training_size = 80% of data; 26709*80% using python slicing

training_size = 21000

training_sentences = sentences[:training_size]
testing_sentences = sentences[training_size:]

# spliting labels into training and testing sets
training_labels = labels[:training_size]
testing_labels = labels[training_size:]


In [20]:
# now tekenize trainig and testing set seperately

tokenizer = Tokenizer(num_words=training_size, oov_token=None)
tokenizer.fit_on_texts(training_sentences)
word_index = tokenizer.word_index

In [21]:
# word_index

training_sequences = tokenizer.texts_to_sequences(training_sentences)
training_paded = pad_sequences(training_sequences)
training_paded

array([[    0,     0,     0, ...,     5,  2711,  9172],
       [    0,     0,     0, ...,   254,     8,   945],
       [    0,     0,     0, ...,    44,     1,  9173],
       ...,
       [    0,     0,     0, ..., 12473,  5960,   496],
       [    0,     0,     0, ...,     3,   363,   311],
       [    0,     0,     0, ...,    19,  3769,   937]], dtype=int32)

In [22]:
testing_sequences = tokenizer.texts_to_sequences(testing_sentences)
testing_paded = pad_sequences(testing_sequences)
testing_paded

array([[    0,     0,     0, ...,   369,  1316,  5075],
       [    0,     0,     0, ...,     0,     0,  5478],
       [    0,     0,     0, ..., 13430,     7, 14891],
       ...,
       [    0,     0,     0, ...,     0,     8,    67],
       [    0,     0,     0, ...,  1724,  3788,  3483],
       [    0,     0,     0, ...,     5,     3,   800]], dtype=int32)

In [23]:
# converting to numpy array explicitely for recent version of tf
training_paded = np.array(training_paded)
training_labels = np.array(training_labels)
testing_paded = np.array(testing_paded)
testing_labels = np.array(testing_labels)

# Model

In [24]:
model = tf.keras.Sequential([
                             tf.keras.layers.Embedding(training_size, output_dim=11),
                             tf.keras.layers.GlobalAveragePooling1D(),
                             tf.keras.layers.Dense(21, activation = 'relu'),
                             tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [25]:
epoch_no = 22
training_texts = model.fit(training_paded, training_labels, epochs=epoch_no,
                           validation_data=(testing_paded, testing_labels), verbose=2)

Epoch 1/22
657/657 - 3s - loss: 0.5950 - accuracy: 0.6805 - val_loss: 0.4396 - val_accuracy: 0.8364
Epoch 2/22
657/657 - 2s - loss: 0.3380 - accuracy: 0.8700 - val_loss: 0.3516 - val_accuracy: 0.8537
Epoch 3/22
657/657 - 2s - loss: 0.2405 - accuracy: 0.9100 - val_loss: 0.3361 - val_accuracy: 0.8564
Epoch 4/22
657/657 - 2s - loss: 0.1821 - accuracy: 0.9347 - val_loss: 0.3409 - val_accuracy: 0.8574
Epoch 5/22
657/657 - 2s - loss: 0.1411 - accuracy: 0.9517 - val_loss: 0.3589 - val_accuracy: 0.8543
Epoch 6/22
657/657 - 2s - loss: 0.1105 - accuracy: 0.9651 - val_loss: 0.3880 - val_accuracy: 0.8501
Epoch 7/22
657/657 - 2s - loss: 0.0871 - accuracy: 0.9730 - val_loss: 0.4138 - val_accuracy: 0.8492
Epoch 8/22
657/657 - 2s - loss: 0.0683 - accuracy: 0.9806 - val_loss: 0.4597 - val_accuracy: 0.8439
Epoch 9/22
657/657 - 2s - loss: 0.0541 - accuracy: 0.9858 - val_loss: 0.4890 - val_accuracy: 0.8432
Epoch 10/22
657/657 - 2s - loss: 0.0424 - accuracy: 0.9894 - val_loss: 0.5431 - val_accuracy: 0.8373

In [26]:
print(training_texts)

# Testing Model on New sentences

In [27]:
# now we can predic any sentence using the model. What ever it bias to sarcastic or not
new_sentences = ['The first step in sentence classification is to represent variable-length sentences using neural networks.', 
             'In this section, I’m going to present the concept of recurrent neural networks (RNNs), one of the most important concepts in deep NLP.', 
             'Many modern NLP models use RNNs in some way.', 
             'I’ll explain why they’re important, what they do, and introduce their simplest variant.']

In [28]:
sequence_sentences = tokenizer.texts_to_sequences(new_sentences)
paded_new_sent = pad_sequences(sequence_sentences)

In [29]:
paded_new_sent

array([[    0,     0,     0,     0,     0,     0,     0,     3,    54,
         1297,     4,  1470,    10,     1,  6175,  7186,   625, 11079],
       [    4,    19,  1972,   117,     1,  3328,     3,  4077,     2,
        11079,    40,     2,     3,    91,   838, 18717,     4,   942],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,   452,  1672,  3569,   340,     4,   153,    89],
       [    0,     0,     0,     0,     0,     0,     0,     0,  1678,
           46,   838,    31,    95,    90,     8,  4868,    93, 13023]],
      dtype=int32)

In [30]:
prediction = model.predict(paded_new_sent)

In [31]:
print(prediction)

[[1.9035932e-12]
 [7.2136223e-03]
 [9.6239793e-01]
 [5.2537048e-01]]


### Ssentiment Analysis in New sentences:
prediction 9 indicating the 4th sentece has a high probability of sarcasm. Less than 5 indicates these sentences are not sercastic at all.

# Training AI to create Poem

In [14]:
from tensorflow.compat.v2.keras.preprocessing.text import Tokenizer

In [9]:
data = """Do not go gentle into that good night,
Old age should burn and rave at close of day;
Rage, rage against the dying of the light.

Though wise men at their end know dark is right,
Because their words had forked no lightning they
Do not go gentle into that good night.

Good men, the last wave by, crying how bright
Their frail deeds might have danced in a green bay,
Rage, rage against the dying of the light.

Wild men who caught and sang the sun in flight,
And learn, too late, they grieved it on its way,
Do not go gentle into that good night.

Grave men, near death, who see with blinding sight
Blind eyes could blaze like meteors and be gay,
Rage, rage against the dying of the light.

And you, my father, there on the sad height,
Curse, bless, me now with your fierce tears, I pray.
Do not go gentle into that good night.
Rage, rage against the dying of the light"""

In [10]:
corpus = data.lower().split('\n')

In [7]:
corpus[0:3]

['do not go gentle into that good night,',
 'old age should burn and rave at close of day;',
 'rage, rage against the dying of the light.']

In [16]:
tokenizer = Tokenizer()
tokenized_corpus = tokenizer.fit_on_texts(corpus[:])

totl_words = len(tokenizer.word_index)+1

input_sequence = []

for line in corpus:
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequence.append(n_gram_sequence)

In [17]:
print(input_sequence)

[[6, 7], [6, 7, 8], [6, 7, 8, 9], [6, 7, 8, 9, 10], [6, 7, 8, 9, 10, 11], [6, 7, 8, 9, 10, 11, 3], [6, 7, 8, 9, 10, 11, 3, 12], [24, 25], [24, 25, 26], [24, 25, 26, 27], [24, 25, 26, 27, 4], [24, 25, 26, 27, 4, 28], [24, 25, 26, 27, 4, 28, 18], [24, 25, 26, 27, 4, 28, 18, 29], [24, 25, 26, 27, 4, 28, 18, 29, 5], [24, 25, 26, 27, 4, 28, 18, 29, 5, 30], [2, 2], [2, 2, 13], [2, 2, 13, 1], [2, 2, 13, 1, 14], [2, 2, 13, 1, 14, 5], [2, 2, 13, 1, 14, 5, 1], [2, 2, 13, 1, 14, 5, 1, 15], [31, 32], [31, 32, 16], [31, 32, 16, 18], [31, 32, 16, 18, 17], [31, 32, 16, 18, 17, 33], [31, 32, 16, 18, 17, 33, 34], [31, 32, 16, 18, 17, 33, 34, 35], [31, 32, 16, 18, 17, 33, 34, 35, 36], [31, 32, 16, 18, 17, 33, 34, 35, 36, 37], [38, 17], [38, 17, 39], [38, 17, 39, 40], [38, 17, 39, 40, 41], [38, 17, 39, 40, 41, 42], [38, 17, 39, 40, 41, 42, 43], [38, 17, 39, 40, 41, 42, 43, 19], [6, 7], [6, 7, 8], [6, 7, 8, 9], [6, 7, 8, 9, 10], [6, 7, 8, 9, 10, 11], [6, 7, 8, 9, 10, 11, 3], [6, 7, 8, 9, 10, 11, 3, 12], [

In [18]:
max_sequence_len = max([len(x) for x in input_sequence])
max_sequence_len

10

In [19]:
input_sequence = np.array(pad_sequences(input_sequence, maxlen=max_sequence_len, padding='pre'))
input_sequence

array([[ 0,  0,  0, ...,  0,  6,  7],
       [ 0,  0,  0, ...,  6,  7,  8],
       [ 0,  0,  0, ...,  7,  8,  9],
       ...,
       [ 0,  0,  0, ...,  1, 14,  5],
       [ 0,  0,  0, ..., 14,  5,  1],
       [ 0,  0,  2, ...,  5,  1, 15]], dtype=int32)

In [20]:
x = input_sequence[:,:-1]
labels = input_sequence[:,-1]

In [21]:
labels

array([ 7,  8,  9, 10, 11,  3, 12, 25, 26, 27,  4, 28, 18, 29,  5, 30,  2,
       13,  1, 14,  5,  1, 15, 32, 16, 18, 17, 33, 34, 35, 36, 37, 17, 39,
       40, 41, 42, 43, 19,  7,  8,  9, 10, 11,  3, 12, 16,  1, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 20, 55, 56, 57,  2, 13,  1, 14,  5,
        1, 15, 16, 21, 59,  4, 60,  1, 61, 20, 62, 63, 64, 65, 19, 66, 67,
       22, 68, 69,  7,  8,  9, 10, 11,  3, 12, 16, 71, 72, 21, 73, 23, 74,
       75, 77, 78, 79, 80, 81,  4, 82, 83,  2, 13,  1, 14,  5,  1, 15, 84,
       85, 86, 87, 22,  1, 88, 89, 91, 92, 93, 23, 94, 95, 96, 97, 98,  7,
        8,  9, 10, 11,  3, 12,  2, 13,  1, 14,  5,  1, 15], dtype=int32)

In [22]:
y = tf.keras.utils.to_categorical(labels, num_classes=totl_words)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

# Now training Neural network with above data

In [23]:
from tensorflow.keras import Sequential
from keras.layers import Embedding
from keras.layers import Bidirectional
from keras.layers import Dense,LSTM

In [24]:
model = Sequential()

In [25]:
model.add(Embedding(totl_words, 99, input_length=max_sequence_len-1))
model.add(Bidirectional(LSTM(50, input_shape=(360,1))))
model.add(Dense(totl_words, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [26]:
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 9, 99)             9801      
_________________________________________________________________
bidirectional (Bidirectional (None, 100)               60000     
_________________________________________________________________
dense (Dense)                (None, 99)                9999      
Total params: 79,800
Trainable params: 79,800
Non-trainable params: 0
_________________________________________________________________
None


In [29]:
history = model.fit(x, y, epochs=100, verbose=1)

Epoch 1/100
5/5 [==============================] - 0s 11ms/step - loss: 0.6525 - accuracy: 0.9866
Epoch 2/100
5/5 [==============================] - 0s 11ms/step - loss: 0.6297 - accuracy: 0.9799
Epoch 3/100
5/5 [==============================] - 0s 11ms/step - loss: 0.6068 - accuracy: 0.9866
Epoch 4/100
5/5 [==============================] - 0s 11ms/step - loss: 0.5862 - accuracy: 0.9799
Epoch 5/100
5/5 [==============================] - 0s 10ms/step - loss: 0.5622 - accuracy: 0.9799
Epoch 6/100
5/5 [==============================] - 0s 10ms/step - loss: 0.5405 - accuracy: 0.9799
Epoch 7/100
5/5 [==============================] - 0s 9ms/step - loss: 0.5196 - accuracy: 0.9933
Epoch 8/100
5/5 [==============================] - 0s 10ms/step - loss: 0.5008 - accuracy: 0.9933
Epoch 9/100
5/5 [==============================] - 0s 10ms/step - loss: 0.4826 - accuracy: 0.9866
Epoch 10/100
5/5 [==============================] - 0s 10ms/step - loss: 0.4674 - accuracy: 0.9933
Epoch 11/100
5/5 [==

# Poet by the model by prediction of next word

In [30]:
seed = 'Do not go gentle into that good night'
next_word = 21

for _ in range(next_word):
  token_list = tokenizer.texts_to_sequences([seed])[0]
  token_list = pad_sequences([token_list], maxlen=max_sequence_len, padding='pre')
  prediction = model.predict_classes(token_list , verbose=0)
  output = ''
  for word, index in tokenizer.word_index.items():
    if index == prediction:
      output = word
      break
  seed = ' ' + output
print(seed)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
 wise
