<a href="https://colab.research.google.com/github/abidshafee/google.colaboratory_projects/blob/master/NLP_Natural_Language_Processing_Using_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tokenization
api involves: **Tokenizer** from **tensorflow->compat.v2->keras->preprocessing.txt**

Given sentences encoding into numbers is calles Tokenization

In [47]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.compat.v2.keras.preprocessing.text import Tokenizer
# from tensorflow.keras.preprocessing.txt import Tokenizer

In [ ]:
sentences = ['The first step in sentence classification is to represent variable-length sentences using neural networks.', 'In this section, I’m going to present the concept of recurrent neural networks (RNNs), one of the most important concepts in deep NLP.', 'Many modern NLP models use RNNs in some way.', 'I’ll explain why they’re important, what they do, and introduce their simplest variant.']

In [24]:
tokenizer = Tokenizer(num_words=100, oov_token='<OOV>')
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
# print(word_index)

In [ ]:
word_index.keys()

dict_keys(['<OOV>', 'in', 'the', 'to', 'neural', 'networks', 'of', 'rnns', 'important', 'nlp', 'first', 'step', 'sentence', 'classification', 'is', 'represent', 'variable', 'length', 'sentences', 'using', 'this', 'section', 'i’m', 'going', 'present', 'concept', 'recurrent', 'one', 'most', 'concepts', 'deep', 'many', 'modern', 'models', 'use', 'some', 'way', 'i’ll', 'explain', 'why', 'they’re', 'what', 'they', 'do', 'and', 'introduce', 'their', 'simplest', 'variant'])

In [ ]:
word_index.values()

dict_values([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

# Organizing text by Sequencing - Turning Sentences into data

In [ ]:
sequences = tokenizer.texts_to_sequences(sentences)
print(sequences)

[[2, 10, 11, 1, 12, 13, 14, 3, 15, 16, 17, 18, 19, 4, 5], [1, 20, 21, 22, 23, 3, 24, 2, 25, 6, 26, 4, 5, 7, 27, 6, 2, 28, 8, 29, 1, 30, 9], [31, 32, 9, 33, 34, 7, 1, 35, 36], [37, 38, 39, 40, 8, 41, 42, 43, 44, 45, 46, 47, 48]]


In [ ]:
# pad_sequences() is a method to handle sentences of different lengths
# best way to handle sentence length is using raggedtensor, we might discuss it in another scope
# but for simplicity we uses here the pad_sequence() to deal with sentence length
padded = pad_sequences(sequences)
print(padded)

# pad_sequences accept parameters are follows: 
#  - padding='post' - will add 0s after the sentences
#  - maxlen=5 - maxlen parameter specify the desire lengh
#  - truncating='post' - specify the choping off the later post if sentence exided 'maxlen'

[[ 0  0  0  0  0  0  0  0  2 10 11  1 12 13 14  3 15 16 17 18 19  4  5]
 [ 1 20 21 22 23  3 24  2 25  6 26  4  5  7 27  6  2 28  8 29  1 30  9]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 31 32  9 33 34  7  1 35 36]
 [ 0  0  0  0  0  0  0  0  0  0 37 38 39 40  8 41 42 43 44 45 46 47 48]]


# Sentiment Analysis - recognize sentiment in text

In [2]:
import json

In [3]:
from google.colab import files
upload = files.upload()

Saving sarcasm.json to sarcasm.json


In [4]:
with open('sarcasm.json', 'r') as f:
  datastore = json.load(f)

In [5]:
sentences = []
labels = []
urls = []

for item in datastore:
  sentences.append(item['headline'])
  labels.append(item['is_sarcastic'])
  urls.append(item['article_link'])

In [15]:
# sentences

In [41]:
# labels
# urls
len(labels)

26709

In [10]:
tokenizer = Tokenizer(oov_token="<OOV>")
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index

In [19]:
# now turning the sentences sequence of token
sequences = tokenizer.texts_to_sequences(sentences)
paded = pad_sequences(sequences, padding='post')

In [21]:
len(sequences)

26709

In [18]:
paded[1]
# paded.shape

array([   4, 8435, 3338, 2746,   22,    2,  166, 8436,  416, 3112,    6,
        258,    9, 1002,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [20]:
paded.shape

(26709, 40)

In [23]:
# now spliting data into traning and testing sets
# let training_size = 80% of data; 26709*80% using python slicing

training_size = 21000

training_sentences = sentences[:training_size]
testing_sentences = sentences[training_size:]

# spliting labels into training and testing sets
training_labels = labels[:training_size]
testing_labels = labels[training_size:]


In [28]:
# now tekenize trainig and testing set seperately

tokenizer = Tokenizer(num_words=training_size, oov_token=None)
tokenizer.fit_on_texts(training_sentences)
word_index = tokenizer.word_index

In [49]:
# word_index

training_sequences = tokenizer.texts_to_sequences(training_sentences)
training_paded = pad_sequences(training_sequences)
training_paded

array([[    0,     0,     0, ...,     5,  2711,  9172],
       [    0,     0,     0, ...,   254,     8,   945],
       [    0,     0,     0, ...,    44,     1,  9173],
       ...,
       [    0,     0,     0, ..., 12473,  5960,   496],
       [    0,     0,     0, ...,     3,   363,   311],
       [    0,     0,     0, ...,    19,  3769,   937]], dtype=int32)

In [35]:
testing_sequences = tokenizer.texts_to_sequences(testing_sentences)
testing_paded = pad_sequences(testing_sequences)
testing_paded

array([[    0,     0,     0, ...,   369,  1316,  5075],
       [    0,     0,     0, ...,     0,     0,  5478],
       [    0,     0,     0, ..., 13430,     7, 14891],
       ...,
       [    0,     0,     0, ...,     0,     8,    67],
       [    0,     0,     0, ...,  1724,  3788,  3483],
       [    0,     0,     0, ...,     5,     3,   800]], dtype=int32)

In [52]:
# converting to numpy array explicitely for recent version of tf
training_paded = np.array(training_paded)
training_labels = np.array(training_labels)
testing_paded = np.array(testing_paded)
testing_labels = np.array(testing_labels)

# Model

In [43]:
model = tf.keras.Sequential([
                             tf.keras.layers.Embedding(training_size, output_dim=11),
                             tf.keras.layers.GlobalAveragePooling1D(),
                             tf.keras.layers.Dense(21, activation = 'relu'),
                             tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [51]:
epoch_no = 30
training_texts = model.fit(trainig_paded, training_labels, epochs=epoch_no,
                           validation_data=(testing_paded, testing_labels), verbose=2)

Epoch 1/30
657/657 - 3s - loss: 0.6009 - accuracy: 0.6710 - val_loss: 0.4306 - val_accuracy: 0.8241
Epoch 2/30
657/657 - 3s - loss: 0.3300 - accuracy: 0.8718 - val_loss: 0.3471 - val_accuracy: 0.8569
Epoch 3/30
657/657 - 3s - loss: 0.2351 - accuracy: 0.9101 - val_loss: 0.3360 - val_accuracy: 0.8560
Epoch 4/30
657/657 - 2s - loss: 0.1782 - accuracy: 0.9351 - val_loss: 0.3475 - val_accuracy: 0.8581
Epoch 5/30
657/657 - 3s - loss: 0.1374 - accuracy: 0.9519 - val_loss: 0.3641 - val_accuracy: 0.8564
Epoch 6/30
657/657 - 2s - loss: 0.1066 - accuracy: 0.9658 - val_loss: 0.3947 - val_accuracy: 0.8516
Epoch 7/30
657/657 - 2s - loss: 0.0837 - accuracy: 0.9734 - val_loss: 0.4350 - val_accuracy: 0.8450
Epoch 8/30
657/657 - 2s - loss: 0.0648 - accuracy: 0.9810 - val_loss: 0.4661 - val_accuracy: 0.8424
Epoch 9/30
657/657 - 2s - loss: 0.0504 - accuracy: 0.9861 - val_loss: 0.5238 - val_accuracy: 0.8392
Epoch 10/30
657/657 - 2s - loss: 0.0387 - accuracy: 0.9900 - val_loss: 0.5662 - val_accuracy: 0.8374